## ndarray的矩阵运算

In [1]:
import numpy as np


In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# 矩阵之间的运算，是按矩阵级的运算，每一个元素和对应索引的运算进行运算
print(arr*arr)
print(arr+arr)

[ 0  1  4  9 16 25 36 49 64 81]
[ 0  2  4  6  8 10 12 14 16 18]


In [4]:
# 广播运算，将标量的广播到数组的各个元素上
print(1+arr)
print(2*arr)


[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18]


## ndarray的切片、索引操作

In [6]:
# 1.一维数组的索引和切片操作
arr1 = np.arange(10)
print(arr1)
print(arr1[5:8])

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]


In [11]:
# 2.多维数组的索引和切片操作

arr2 = np.arange(10).reshape(2, 5)
print(arr2)
# 二维数组的索引和切片操作，[]里的第一个数字表示行所在的索引，第二个表示列所在的索引
print(arr2[1, :3])
# 如果某个数字只有一个 冒号:，那就表示全部匹配
print(arr2[: , :3])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7]
[[0 1 2]
 [5 6 7]]


## ndarray的条件索引

In [13]:
a = np.array([[2010, 1022, 24092], [121, 12443, 25], [354, 67, 787]])
print(a)

[[ 2010  1022 24092]
 [  121 12443    25]
 [  354    67   787]]


In [15]:
# 将数组的每个元素和条件进行匹配，返回每个元素的匹配结果，是bool值
b = a>2000
print(b)

[[ True False  True]
 [False  True False]
 [False False False]]


In [16]:
arr2 = np.random.randn(3, 3)
print(arr2)

[[ 1.34908424  0.03004682 -2.02255103]
 [-0.13208472  0.23939292  0.37355604]
 [ 0.55675008 -0.22063762 -0.28812348]]


In [18]:
# 将bool数组，映射到arr2,返回匹配为true的数值，返回的一维数组
new_arr2 = arr2[b]
print(new_arr2)

[ 1.34908424 -2.02255103  0.23939292]


In [20]:
# 2.可以同时制定多个条件索引，&表示所有条件都符合，结果才为True，|表条件符合，只要有一个符合条件结果就是True
# 实例中：将多个条件索引返回的匹配结果，映射到新的数组上，返回匹配为true的一维数组
new_arr2 = arr2[(a>1)&(a<10000)]
print(new_arr2)

[ 1.34908424  0.03004682 -0.13208472  0.37355604  0.55675008 -0.22063762
 -0.28812348]


## ndarray的维数转换 transpose()

In [25]:
# transponse()将转换原数组的维度，如果是二维数组不需要指定参数
arr2 = np.random.rand(3,4)
print(arr2)
print("---------------")
print(arr2.transpose())

[[ 0.4436276   0.10188303  0.91512317  0.54276986]
 [ 0.17110179  0.53730995  0.67721354  0.0012474 ]
 [ 0.85587238  0.76458056  0.35069948  0.17626608]]
---------------
[[ 0.4436276   0.17110179  0.85587238]
 [ 0.10188303  0.53730995  0.76458056]
 [ 0.91512317  0.67721354  0.35069948]
 [ 0.54276986  0.0012474   0.17626608]]


In [28]:
# 如果是多维数组，如3维数组，则transpose()里的参数是一个元祖。原则的每个元素都是原来数组维度的索引值
# 4对应的索引是2， 3对应的索引是1， 2对应的索引是0， 则转换是写上索引即可
arr3 = np.random.rand(2,3,4)
print(arr3)
print("-----")
print(arr3.transpose(2,0,1))

[[[ 0.70335763  0.20772979  0.97008075  0.98744339]
  [ 0.02941858  0.03282165  0.74315847  0.76207509]
  [ 0.86487291  0.02356911  0.4578792   0.60194893]]

 [[ 0.56612036  0.26512351  0.925407    0.08102814]
  [ 0.47334917  0.38101436  0.21830038  0.18570292]
  [ 0.59132532  0.64750665  0.27868175  0.86660637]]]
-----
[[[ 0.70335763  0.02941858  0.86487291]
  [ 0.56612036  0.47334917  0.59132532]]

 [[ 0.20772979  0.03282165  0.02356911]
  [ 0.26512351  0.38101436  0.64750665]]

 [[ 0.97008075  0.74315847  0.4578792 ]
  [ 0.925407    0.21830038  0.27868175]]

 [[ 0.98744339  0.76207509  0.60194893]
  [ 0.08102814  0.18570292  0.86660637]]]
