In [1]:
import numpy as np

In [2]:
arr = np.random.randn(3,4)
arr

array([[ 0.9115296 , -0.44337692,  0.86541395, -0.31257523],
       [-0.11475089, -0.97262504, -1.72447134, -1.52402506],
       [ 1.35851444, -1.02441338,  0.4308067 ,  2.74452237]])

In [3]:
# 取最近比自己大的整数
print(np.ceil(arr))

[[ 1. -0.  1. -0.]
 [-0. -0. -1. -1.]
 [ 2. -1.  1.  3.]]


In [4]:
# 取最近比自己小的整数
print(np.floor(arr))


[[ 0. -1.  0. -1.]
 [-1. -1. -2. -2.]
 [ 1. -2.  0.  2.]]


In [5]:
# 四舍五入
print(np.rint(arr))

[[ 1. -0.  1. -0.]
 [-0. -1. -2. -2.]
 [ 1. -1.  0.  3.]]


In [6]:
# 取每个元素的绝对值
print(np.abs(arr))

[[ 0.9115296   0.44337692  0.86541395  0.31257523]
 [ 0.11475089  0.97262504  1.72447134  1.52402506]
 [ 1.35851444  1.02441338  0.4308067   2.74452237]]


In [8]:
# NAN =  not a number表示不是一个可以用来计算的数值
# 可以创建一个nan数值
num = np.nan
print(np.isnan(arr))
print(np.isnan(num))

[[False False False False]
 [False False False False]
 [False False False False]]
True


In [10]:
# 数组和数组之间每个元素相乘，返回计算后的数组
# 参数可以是数组，也可以是数字
print(arr)
print(np.multiply(arr,arr))
print(np.multiply(arr[2,3], arr[0,1]))

[[ 0.9115296  -0.44337692  0.86541395 -0.31257523]
 [-0.11475089 -0.97262504 -1.72447134 -1.52402506]
 [ 1.35851444 -1.02441338  0.4308067   2.74452237]]
[[ 0.83088621  0.1965831   0.74894131  0.09770328]
 [ 0.01316777  0.94599948  2.97380141  2.32265237]
 [ 1.84556148  1.04942277  0.18559441  7.53240306]]
-1.21685788939


In [11]:
# 相除
print(np.divide(arr, arr))
print(np.divide(arr[2,3], arr[0,2]))


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
3.17134057107


In [12]:
# 三目运算符，三元运算符
# 包含三个参数，第一个参数是条件语句，第二个参数是条件为真返回值，第三个参数是条件为假的返回值
print(np.where(arr<0,-1,0))

[[ 0 -1  0 -1]
 [-1 -1 -1 -1]
 [ 0 -1  0  0]]


# ndarray的统计函数

In [13]:
arr = np.random.randint(0,10,(3,4))
print(arr)

[[9 8 5 8]
 [6 6 7 7]
 [7 9 7 8]]


In [14]:
# 求数字里所有元素的平均值
print(np.mean(arr))

7.25


In [17]:
# 求数组里所有元素的和
print(np.sum(arr))

87


In [18]:
# 求数组里的最大值
print(np.max(arr))


9


In [20]:
# 求数组里的最小值
print(np.min(arr))

5


In [21]:
# 衡量数据和期望值之间的偏离值

In [22]:
# 标准差，就是所有元素分别和平均值的差 的和 的平均数
print(np.std(arr))


1.16368667031


In [23]:
# 方差：就是所有元素分别和平均数的差，的平方，的和， 的平均数
print(np.var(arr))


1.35416666667


In [24]:
# 如果是多维数组，将多维合并为一维数组，再找到第一个最大值的索引下标
# 如果是一维数组，则找到第一个最大值的索引下标
print(np.argmax(arr))


0


In [25]:
# 求最小值的索引下标
print(np.argmin(arr))

2


In [26]:
# 返回一个一维数组，数组的每个元素都是之前所有元素的累加的和
print(arr)
print(np.cumsum(arr))

[[9 8 5 8]
 [6 6 7 7]
 [7 9 7 8]]
[ 9 17 22 30 36 42 49 56 63 72 79 87]


In [28]:
# 返回一个一维数组，数组的每个元素都是之前所有元素的累乘的积
print(np.cumprod(arr))

[          9          72         360        2880       17280      103680
      725760     5080320    35562240   320060160 -2054546176   743499776]


## 元素的判断函数

In [30]:
arr =np.random.rand(3, 4)
print(arr)

[[ 0.9056916   0.70913761  0.04194702  0.14776115]
 [ 0.82454813  0.33611229  0.41594847  0.14853794]
 [ 0.73559397  0.18586652  0.80770814  0.80145374]]


In [33]:
# 数组里有任意一个元素满足条件，返回True
print(np.any(arr>10))

False


In [34]:
# 数组里所有元素满足条件，返回True
print(np.all(arr>0.5))


False
