## NumPy

ndarray的随机创建

In [1]:
# 导入numpy，别名是np
import numpy as np

In [2]:
# random表示常见的随机数，rand表示创建一个随机浮点数组，参数个数变数维度的大小
# 默认的区间是0.0-0.1之间
arr = np.random.rand(3,4)
print(arr)
print(type(arr))
# ndim参数表示数组的维度
print(arr.ndim)

# shape 参数表示数据的大小
print(arr.shape)
# dtype 表示每个数组的类型
print(arr.dtype)


[[ 0.870892    0.91548663  0.0248226   0.1591814 ]
 [ 0.46902906  0.32895097  0.82706097  0.09981212]
 [ 0.04020235  0.75217794  0.7617957   0.50298033]]
<class 'numpy.ndarray'>
2
(3, 4)
float64


In [4]:
# 生成一个符合标准正态分布的随机浮点数组
arr = np.random.randn(1000)
#print(arr)


In [5]:
# 创建一个3行4列的二维整数数组，每个元素的值得区间在-10~20之间
arr = np.random.randint(-10,20, size = (3,4))
print(arr)

[[  4  12 -10   5]
 [  8  -9  -5  -4]
 [ 10   6  -3  -4]]


In [6]:
# 创建一个3行4列的二维浮点数组，每个元素的值得区间在-10~20之间
arr = np.random.uniform(-10, 20, (3, 4)) # size=可以省略不写
print(arr)

[[ -5.60912561   3.43869256   2.92418409  15.45765602]
 [ 13.21220023  -1.28143246   4.42122765  14.53247327]
 [ -2.42163965  -3.70277836   0.12730163   2.01670471]]


## ndarray的序列创建

In [11]:
# lis是range类型, 包含了0~10的数据的迭代器
lis = range(10)
# 把lis作为np.array()的参数，则会创建一个包含0~10的10个元素的一维数组对象
arr = np.array(list)
print(arr)

<class 'list'>


In [12]:
# array()参数可以使多维的数组
#下面的示例，便是创建了一个三维的数组，数组里包含了两个二维数组
# 每个二维数组包含了两个一维数组
# 每一一维数组包含了10个元素
arr2 = np.array([[list, list],[list, list]])
print(arr2)

[[<class 'list'> <class 'list'>]
 [<class 'list'> <class 'list'>]]


In [15]:
# 创建一个3行4列的二维数组，默认数组的每个元素都是float64树泽的
# 第二个参数可以指定数据类型
arr3 = np.zeros((3,4), int)
print(arr3)
print(arr3.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [17]:
# 创建一个3行4列的二维数组，默认数组的每个元素都是float64类型的
# 第二个参数可以指定数据类型
arr4  =np.ones((3, 4), int)
print(arr4)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [19]:
# 初始化数组，不指定具体的数值，里面的值有可能是0， 有可能不是0， 默认数组的每个元素都是FLOAT64乐类型
# 第二个参数可以指定数据类型
arr5 = np.empty((3,4), int)
print(arr5)

[[234   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]]


## ndarray 的arange和reshape

In [20]:
# arange() 类似 python 的 range() ，创建一个一维 ndarray 数组。
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
# reshape() 将 重新调整数组的维数。
arr2  =arr.reshape(2,5)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [24]:
# 将十个元素的一维数组改变为 一个三维数组,一个三维数组，包含两个二维数组，里面有5个元素
arr3 = arr.reshape(1,2,5)
print(arr3)

[[[0 1 2 3 4]
  [5 6 7 8 9]]]


In [26]:
# 随机打乱原数组的序列
np.random.shuffle(arr)
print(arr)

[3 8 5 2 4 6 0 7 9 1]


## 数组的数据类型的转换


In [27]:
zero_float  = np.zeros((3, 4))
print(zero_float)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [28]:
zero_int = zero_float .astype(np.int32)
print(zero_int)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
