# 数据合并(pd.concat)

In [1]:
# 表示相同字段的数据进行首尾连接

In [14]:
import numpy as np
import pandas as pd


In [15]:
# 1.Numpy 里的concatenate
arr1 = np.random.randint(0,10,(3,4))
arr2 = np.random.randint(0,10,(3,4))
print(arr1)
print(arr2)
print("*"*50)
# 默认轴的方向是列，两个数组列部分首尾连接（6*3）
print(np.concatenate([arr1, arr2]))
print("*"*10)
# axis的轴方向是行， 那么就是两个数的行部分首尾连接（3*6）
print(np.concatenate([arr1, arr2], axis = 1))

[[5 6 2 0]
 [8 7 8 1]
 [1 2 7 9]]
[[3 4 8 0]
 [7 1 1 0]
 [4 6 8 2]]
**************************************************
[[5 6 2 0]
 [8 7 8 1]
 [1 2 7 9]
 [3 4 8 0]
 [7 1 1 0]
 [4 6 8 2]]
**********
[[5 6 2 0 3 4 8 0]
 [8 7 8 1 7 1 1 0]
 [1 2 7 9 4 6 8 2]]


In [16]:
# 2.pandas里的concat

In [19]:
# 2.1 index没有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index = range(0,5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index = range(5,9))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index = range(9, 12))
print(ser_obj1)
print(ser_obj2)
print(ser_obj3)
# 默认是按列运行连接，默认是外连接
print(pd.concat([ser_obj1, ser_obj2, ser_obj3]))
# axis = 1 按行连接， 默认为外连接
# print(pd.concat([ser_obj1,ser_obj2, ser_obj3], axis  = 1))
# 默认“outer”是外连接， json = ‘outer’表示为内连接，（数据是交集）
#print(pd.concat([ser_obj1, ser_obj2, ser_obj3], axis = 1, join="inner"))

# print(pd.concat([ser_obj1, ser_obj2, ser_obj3], join="inner"))

0    8
1    1
2    9
3    0
4    4
dtype: int32
5    6
6    9
7    3
8    4
dtype: int32
9     5
10    3
11    7
dtype: int32
0     8
1     1
2     9
3     0
4     4
5     6
6     9
7     3
8     4
9     5
10    3
11    7
dtype: int32


In [22]:
# 2.2 index有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index = range(5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index = range(4))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index = range(3))
print(ser_obj1)
print(ser_obj2)
print(ser_obj3)
print("*"*50)
# 默认是按列进行连接，默认外连接
#print(pd.concat([ser_obj1, ser_obj2, ser_obj3]))

# axis = 1 按行连接，默认外连接
#print(pd.concat([ser_obj1, ser_obj2, ser_obj3], axis = 1))

# 默认"outer"是外连接，join = "inner" 表示内连接（数据是交集）
# 如果没有交集的数据，则去除NaN所在的行/列
print(pd.concat([ser_obj1, ser_obj2, ser_obj3], axis = 1, join="inner"))

# print(pd.concat([ser_obj1, ser_obj2, ser_obj3], join="inner"))

0    0
1    0
2    7
3    4
4    5
dtype: int32
0    5
1    4
2    9
3    3
dtype: int32
0    4
1    9
2    9
dtype: int32
**************************************************
   0  1  2
0  0  5  4
1  0  4  9
2  7  9  9


In [26]:
# DataFrame 
df_obj1 = pd.DataFrame(np.random.randint(0, 10, (3, 2)), index=['a', 'b', 'c'],
                       columns=['A', 'B'])
df_obj2 = pd.DataFrame(np.random.randint(0, 10, (2, 2)), index=['a', 'b'],
                       columns=['C', 'D'])
print(df_obj1)
print(df_obj2)

   A  B
a  7  0
b  4  4
c  9  9
   C  D
a  5  7
b  5  1


In [27]:
#　默认是按行连接
#print(pd.concat([df_obj1, df_obj2]))
# 指定轴方向，通知按内连接(NaN所在的行/列将被去除)
print(pd.concat([df_obj1, df_obj2], axis = 1, join= "inner"))

   A  B  C  D
a  7  0  5  7
b  4  4  5  1
